ckanext/pygments/views.py
from __future__ import annotations

import logging

from flask import Blueprint

import ckan.plugins as p
import ckan.plugins.toolkit as tk

import ckanext.pygments.cache as pygments_cache
import ckanext.pygments.config as pygment_config
import ckanext.pygments.utils as pygments_utils

log = logging.getLogger(__name__)
bp = Blueprint("pygments", __name__, url_prefix="/pygments")


@bp.route("/highlight/<resource_id>", methods=["GET"])
def highlight(resource_id: str) -> str:
    cache_manager = pygments_cache.RedisCache()
    cache_enabled = pygment_config.is_cache_enabled()
    resource_view_id = tk.request.args.get("resource_view_id", type=str)
    preview = ""

    if cache_enabled:
        preview = cache_manager.get_data(resource_id, resource_view_id)

        if len(preview) > pygment_config.get_resource_cache_max_size():
            cache_manager.invalidate(resource_id)

    if preview:
        return tk.render("pygments/pygment_preview_body.html", {"preview": preview})

    try:
        preview = pygments_utils.pygment_preview(
            resource_id,
            tk.request.args.get("theme", pygment_config.get_default_theme(), type=str),
            tk.request.args.get("max_size", pygment_config.get_resource_cache_max_size(), type=int),
            tk.request.args.get("file_url", type=str),
            tk.asbool(tk.request.args.get("show_line_numbers", "False")),
        )
    except Exception:
        log.exception(
            "Pygments: failed to render preview, resource_id: %s",
            resource_id,
        )
        preview = "Pygments: Error rendering preview. Please, contact the administrator."
    else:
        if cache_enabled and not len(preview) > pygment_config.get_resource_cache_max_size():
            cache_manager.set_data(resource_id, preview, resource_view_id)

    return tk.render("pygments/pygment_preview_body.html", {"preview": preview})


@bp.route("/clear_cache", methods=["POST"])
def clear_cache():
    pygments_cache.RedisCache.drop_cache()

    tk.h.flash_success(tk._("Cache has been cleared"))

    if p.plugin_loaded("admin_panel"):
        return tk.h.redirect_to("pygments_admin.config")

    return "Cache has been cleared"


@bp.route("/clear_cache/<resource_id>", methods=["POST"])
def clear_resource_cache(resource_id: str):
    pygments_cache.RedisCache().invalidate(resource_id, tk.request.args.get("resource_view_id", type=str))

    if p.plugin_loaded("admin_panel"):
        return tk.h.redirect_to("pygments_admin.config")

    return "Resource cache has been cleared"


if p.plugin_loaded("admin_panel"):
    from ckanext.ap_main.utils import ap_before_request
    from ckanext.ap_main.views.generics import ApConfigurationPageView

    pygments_admin = Blueprint("pygments_admin", __name__)
    pygments_admin.before_request(ap_before_request)

    pygments_admin.add_url_rule(
        "/admin-panel/pygments/config",
        view_func=ApConfigurationPageView.as_view(
            "config",
            "pygments_config",
            render_template="pygments/config.html",
            page_title=tk._("Pygments config"),
        ),
    )

ckanext/pygments/templates/package/snippets/resource_view.html
{% ckan_extends %}

{% block resource_view %}
    {% if resource_view.view_type == "pygments_view" %}
    <div class="pygments-info">
        {% if g.userobj.sysadmin and h.pygments_is_cache_enabled()%}
            {% set clear_cache_url = h.url_for('pygments.clear_resource_cache', resource_id=resource.id) %}

            {% if resource_view.file_url %}
                {% set clear_cache_url = h.url_for('pygments.clear_resource_cache', resource_id=resource.id, resource_view_id=resource_view.id if resource_view.file_url else "") %}
            {% endif %}

            <button
                class="btn btn-default btn-pygment-refresh"
                hx-post="{{ clear_cache_url }}"
                hx-swap="none">
                <i class="fa fa-trash"></i>
                {{ _("Clear cache") }}
            </button>

            <span><b>{{ _("Memory usage") }}:</b></span>
            <span>{{ _("Total") }}: {{ h.pygments_printable_file_size(h.pygments_get_cache_size()) }}</span>
            <span>{{ _("Current") }}: {{ h.pygments_printable_file_size(h.pygments_get_resource_view_cache_size(resource.id, resource_view.id if resource_view.file_url else "")) }}</span>
        {% endif %}
    </div>
    {% endif %}

    {{ super() }}
{% endblock %}

ckanext/pygments/templates/package/snippets/view_form.html
{% ckan_extends %}

{% block view_form_filters %}
    {% if data.view_type != "pygments_view" %}
        {% snippet 'package/snippets/view_form_filters.html', resource=resource, resource_view=resource_view %}
    {% endif %}
{% endblock %}

ckanext/pygments/templates/pygment_form.html
{% import 'macros/form.html' as form %}

{{ form.input(
    'file_url',
    id='field-file_url',
    label=_('File URL'),
    placeholder=_('eg. http://example.com/test.sql  (if blank uses resource url)'),
    value=data.file_url,
    error=errors.file_url)
}}

{{ form.select(
    'theme',
    id='field-theme',
    label=_('Preview theme'),
    options=h.get_preview_theme_options(),
    selected=data.theme or "default",
    error=errors.theme)
}}

{% call form.input(
    'size',
    id='field-size',
    label=_('Max size to render'),
    value=data.size or h.get_default_max_size(),
    error=errors.size) %}
        {{ form.info(_('Specifies how many bytes from file we are going to render with ckanext-pygment. Set to `-1` if you want to disable a limit. This can cause the page to load very slowly.', classes=['info-help-tight'])) }}
{% endcall %}

ckanext/pygments/templates/pygments/config.html
{% extends 'admin_panel/config/autogenerated_config.html' %}

{% block before_form %}
    <form method="POST" action="{{ h.url_for('pygments.clear_cache') }}" class="mb-3">
        {{ h.csrf_input() }}

        <div class="pygments-info">
            <button type="submit" name="invalidate-all-cache" value="clear_cache" class="btn btn-primary">
                </i>{{ _('Invalidate cache') }}
            </button>

            <span><b>{{ _("Memory usage") }}:</b></span>
            <span>{{ h.pygments_printable_file_size(h.pygments_get_cache_size()) }}</span>
        </div>
    </form>
{% endblock %}

ckanext/pygments/templates/pygments/pygment_form.html
{% import 'macros/form.html' as form %}

{% call form.input(
    'file_url',
    id='field-file_url',
    label=_('File URL'),
    placeholder=_('eg. http://example.com/test.sql  (if blank uses resource url)'),
    value=data.file_url,
    error=errors.file_url) %}
    {{ form.info(_('If you wish to retrieve remote data for this view, you may specify the URL.', classes=['info-help-tight'])) }}
{% endcall %}

{{ form.select(
    'theme',
    id='field-theme',
    label=_('Preview theme'),
    options=h.pygments_get_preview_theme_options(),
    selected=data.theme or h.pygments_get_default_theme(),
    attrs={'data-module': 'autocomplete'},
    error=errors.theme)
}}

{% call form.input(
    'max_size',
    id='field-max_size',
    label=_('Max size to render'),
    value=data.max_size or h.pygments_get_default_max_size(),
    error=errors.max_size) %}
        {{ form.info(_('Specifies how many bytes from file we are going to render. Set to `-1` if you want to disable a limit. <i class="fa fa-warning"></i> This can cause the page to load very slowly.', classes=['info-help-tight'])) }}
{% endcall %}

{% call form.select(
    'show_line_numbers',
    id='field-show_line_numbers',
    label=_('Show Line Numbers'),
    options=[{"value": "yes", "text": _("Yes")}, {"value": "no", "text": _("No")}],
    selected='yes' if data.show_line_numbers else 'no',
    error=errors.show_line_numbers) %}
        {{ form.info(_('Choose whether to display line numbers in the code preview.', classes=['info-help-tight'])) }}
{% endcall %}

ckanext/pygments/templates/pygments/pygment_indicator.html
<svg width="24" height="24" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
    <style>
        .spinner_zWVm {
            animation: spinner_5QiW 1.2s linear infinite, spinner_PnZo 1.2s linear infinite
        }

        .spinner_gfyD {
            animation: spinner_5QiW 1.2s linear infinite, spinner_4j7o 1.2s linear infinite;
            animation-delay: .1s
        }

        .spinner_T5JJ {
            animation: spinner_5QiW 1.2s linear infinite, spinner_fLK4 1.2s linear infinite;
            animation-delay: .1s
        }

        .spinner_E3Wz {
            animation: spinner_5QiW 1.2s linear infinite, spinner_tDji 1.2s linear infinite;
            animation-delay: .2s
        }

        .spinner_g2vs {
            animation: spinner_5QiW 1.2s linear infinite, spinner_CMiT 1.2s linear infinite;
            animation-delay: .2s
        }

        .spinner_ctYB {
            animation: spinner_5QiW 1.2s linear infinite, spinner_cHKR 1.2s linear infinite;
            animation-delay: .2s
        }

        .spinner_BDNj {
            animation: spinner_5QiW 1.2s linear infinite, spinner_Re6e 1.2s linear infinite;
            animation-delay: .3s
        }

        .spinner_rCw3 {
            animation: spinner_5QiW 1.2s linear infinite, spinner_EJmJ 1.2s linear infinite;
            animation-delay: .3s
        }

        .spinner_Rszm {
            animation: spinner_5QiW 1.2s linear infinite, spinner_YJOP 1.2s linear infinite;
            animation-delay: .4s
        }

        @keyframes spinner_5QiW {

            0%,
            50% {
                width: 7.33px;
                height: 7.33px
            }

            25% {
                width: 1.33px;
                height: 1.33px
            }
        }

        @keyframes spinner_PnZo {

            0%,
            50% {
                x: 1px;
                y: 1px
            }

            25% {
                x: 4px;
                y: 4px
            }
        }

        @keyframes spinner_4j7o {

            0%,
            50% {
                x: 8.33px;
                y: 1px
            }

            25% {
                x: 11.33px;
                y: 4px
            }
        }

        @keyframes spinner_fLK4 {

            0%,
            50% {
                x: 1px;
                y: 8.33px
            }

            25% {
                x: 4px;
                y: 11.33px
            }
        }

        @keyframes spinner_tDji {

            0%,
            50% {
                x: 15.66px;
                y: 1px
            }

            25% {
                x: 18.66px;
                y: 4px
            }
        }

        @keyframes spinner_CMiT {

            0%,
            50% {
                x: 8.33px;
                y: 8.33px
            }

            25% {
                x: 11.33px;
                y: 11.33px
            }
        }

        @keyframes spinner_cHKR {

            0%,
            50% {
                x: 1px;
                y: 15.66px
            }

            25% {
                x: 4px;
                y: 18.66px
            }
        }

        @keyframes spinner_Re6e {

            0%,
            50% {
                x: 15.66px;
                y: 8.33px
            }

            25% {
                x: 18.66px;
                y: 11.33px
            }
        }

        @keyframes spinner_EJmJ {

            0%,
            50% {
                x: 8.33px;
                y: 15.66px
            }

            25% {
                x: 11.33px;
                y: 18.66px
            }
        }

        @keyframes spinner_YJOP {

            0%,
            50% {
                x: 15.66px;
                y: 15.66px
            }

            25% {
                x: 18.66px;
                y: 18.66px
            }
        }
    </style>
    <rect class="spinner_zWVm" x="1" y="1" width="7.33" height="7.33" />
    <rect class="spinner_gfyD" x="8.33" y="1" width="7.33" height="7.33" />
    <rect class="spinner_T5JJ" x="1" y="8.33" width="7.33" height="7.33" />
    <rect class="spinner_E3Wz" x="15.66" y="1" width="7.33" height="7.33" />
    <rect class="spinner_g2vs" x="8.33" y="8.33" width="7.33" height="7.33" />
    <rect class="spinner_ctYB" x="1" y="15.66" width="7.33" height="7.33" />
    <rect class="spinner_BDNj" x="15.66" y="8.33" width="7.33" height="7.33" />
    <rect class="spinner_rCw3" x="8.33" y="15.66" width="7.33" height="7.33" />
    <rect class="spinner_Rszm" x="15.66" y="15.66" width="7.33" height="7.33" />
</svg>

ckanext/pygments/templates/pygments/pygment_preview.html
{% set preview_url = h.url_for(
    'pygments.highlight',
    resource_id=resource.id,
    theme=resource_view.theme,
    max_size=resource_view.max_size,
    file_url=resource_view.file_url,
    resource_view_id=resource_view.id if resource_view.file_url else '',
    show_line_numbers=resource_view.show_line_numbers
) %}

<div
    hx-target="this"
    hx-trigger="load delay:1ms, htmx:afterRequest from:.btn-pygment-refresh"
    hx-get="{{ preview_url }}"
    {% if h.pygments_is_cache_enabled() %}hx-disabled-elt=".btn-pygment-refresh, .ckanext-datapreview"{% endif %}>
    <span>
        {% snippet "pygments/pygment_indicator.html" %}
        {{ _("Preparing your preview...") }}
    </span>
</div>

{% if h.pygments_include_htmx_asset() %}
    {% asset "pygments/pygments-js-htmx" %}
{% endif %}

{% asset 'pygments/pygments-css' %}

ckanext/pygments/templates/pygments/pygment_preview_body.html
<span id="pygments-spinner">
    {% snippet "pygments/pygment_indicator.html" %}
    {{ _("Updating your preview...") }}
</span>

<div class="highlight pygments-highlight">
    {{ preview | safe }}
</div>